/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ToastOptions } from "./components/ng-toastify-stencil/ng-toastify-stencil";
export { ToastOptions } from "./components/ng-toastify-stencil/ng-toastify-stencil";
export namespace Components {
    interface NgToastifyStencil {
        "Toast": (toast: ToastOptions) => Promise<void>;
    }
    interface NgToastifyStencilContent {
        /**
          * @default true
         */
        "allowClose": boolean;
        /**
          * @default 'success message'
         */
        "description": string;
        /**
          * @default 'Success'
         */
        "toastTitle": string;
        /**
          * @default 'success'
         */
        "type": string;
        "typeBgColor": string;
        "typeIcon": any;
        "typeTextColor": string;
    }
}
declare global {
    interface HTMLNgToastifyStencilElement extends Components.NgToastifyStencil, HTMLStencilElement {
    }
    var HTMLNgToastifyStencilElement: {
        prototype: HTMLNgToastifyStencilElement;
        new (): HTMLNgToastifyStencilElement;
    };
    interface HTMLNgToastifyStencilContentElement extends Components.NgToastifyStencilContent, HTMLStencilElement {
    }
    var HTMLNgToastifyStencilContentElement: {
        prototype: HTMLNgToastifyStencilContentElement;
        new (): HTMLNgToastifyStencilContentElement;
    };
    interface HTMLElementTagNameMap {
        "ng-toastify-stencil": HTMLNgToastifyStencilElement;
        "ng-toastify-stencil-content": HTMLNgToastifyStencilContentElement;
    }
}
declare namespace LocalJSX {
    interface NgToastifyStencil {
    }
    interface NgToastifyStencilContent {
        /**
          * @default true
         */
        "allowClose"?: boolean;
        /**
          * @default 'success message'
         */
        "description"?: string;
        /**
          * @default 'Success'
         */
        "toastTitle"?: string;
        /**
          * @default 'success'
         */
        "type"?: string;
        "typeBgColor"?: string;
        "typeIcon"?: any;
        "typeTextColor"?: string;
    }
    interface IntrinsicElements {
        "ng-toastify-stencil": NgToastifyStencil;
        "ng-toastify-stencil-content": NgToastifyStencilContent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ng-toastify-stencil": LocalJSX.NgToastifyStencil & JSXBase.HTMLAttributes<HTMLNgToastifyStencilElement>;
            "ng-toastify-stencil-content": LocalJSX.NgToastifyStencilContent & JSXBase.HTMLAttributes<HTMLNgToastifyStencilContentElement>;
        }
    }
}
