/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ToastOptions } from "./components/hey-toast/hey-toast";
export { ToastOptions } from "./components/hey-toast/hey-toast";
export namespace Components {
    interface HeyToast {
        "Toast": (toast: ToastOptions) => Promise<void>;
    }
    interface HeyToastContent {
        /**
          * @default true
         */
        "allowClose": boolean;
        /**
          * @default 'success message'
         */
        "description": string;
        /**
          * @default 'Success'
         */
        "toastTitle": string;
        /**
          * @default 'success'
         */
        "type": string;
        "typeBgColor": string;
        "typeIcon": any;
        "typeTextColor": string;
    }
}
declare global {
    interface HTMLHeyToastElement extends Components.HeyToast, HTMLStencilElement {
    }
    var HTMLHeyToastElement: {
        prototype: HTMLHeyToastElement;
        new (): HTMLHeyToastElement;
    };
    interface HTMLHeyToastContentElement extends Components.HeyToastContent, HTMLStencilElement {
    }
    var HTMLHeyToastContentElement: {
        prototype: HTMLHeyToastContentElement;
        new (): HTMLHeyToastContentElement;
    };
    interface HTMLElementTagNameMap {
        "hey-toast": HTMLHeyToastElement;
        "hey-toast-content": HTMLHeyToastContentElement;
    }
}
declare namespace LocalJSX {
    interface HeyToast {
    }
    interface HeyToastContent {
        /**
          * @default true
         */
        "allowClose"?: boolean;
        /**
          * @default 'success message'
         */
        "description"?: string;
        /**
          * @default 'Success'
         */
        "toastTitle"?: string;
        /**
          * @default 'success'
         */
        "type"?: string;
        "typeBgColor"?: string;
        "typeIcon"?: any;
        "typeTextColor"?: string;
    }
    interface IntrinsicElements {
        "hey-toast": HeyToast;
        "hey-toast-content": HeyToastContent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hey-toast": LocalJSX.HeyToast & JSXBase.HTMLAttributes<HTMLHeyToastElement>;
            "hey-toast-content": LocalJSX.HeyToastContent & JSXBase.HTMLAttributes<HTMLHeyToastContentElement>;
        }
    }
}
