/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ToastOptions } from "./components/ng-toastify/ng-toastify";
export { ToastOptions } from "./components/ng-toastify/ng-toastify";
export namespace Components {
    interface NgToastify {
        "Toast": (toast: ToastOptions) => Promise<void>;
    }
    interface NgToastifyContent {
        /**
          * @default true
         */
        "allowClose": boolean;
        /**
          * @default 'success message'
         */
        "description": string;
        /**
          * @default 'Success'
         */
        "toastTitle": string;
        /**
          * @default 'success'
         */
        "type": string;
        "typeBgColor": string;
        "typeIcon": any;
        "typeTextColor": string;
    }
}
declare global {
    interface HTMLNgToastifyElement extends Components.NgToastify, HTMLStencilElement {
    }
    var HTMLNgToastifyElement: {
        prototype: HTMLNgToastifyElement;
        new (): HTMLNgToastifyElement;
    };
    interface HTMLNgToastifyContentElement extends Components.NgToastifyContent, HTMLStencilElement {
    }
    var HTMLNgToastifyContentElement: {
        prototype: HTMLNgToastifyContentElement;
        new (): HTMLNgToastifyContentElement;
    };
    interface HTMLElementTagNameMap {
        "ng-toastify": HTMLNgToastifyElement;
        "ng-toastify-content": HTMLNgToastifyContentElement;
    }
}
declare namespace LocalJSX {
    interface NgToastify {
    }
    interface NgToastifyContent {
        /**
          * @default true
         */
        "allowClose"?: boolean;
        /**
          * @default 'success message'
         */
        "description"?: string;
        /**
          * @default 'Success'
         */
        "toastTitle"?: string;
        /**
          * @default 'success'
         */
        "type"?: string;
        "typeBgColor"?: string;
        "typeIcon"?: any;
        "typeTextColor"?: string;
    }
    interface IntrinsicElements {
        "ng-toastify": NgToastify;
        "ng-toastify-content": NgToastifyContent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ng-toastify": LocalJSX.NgToastify & JSXBase.HTMLAttributes<HTMLNgToastifyElement>;
            "ng-toastify-content": LocalJSX.NgToastifyContent & JSXBase.HTMLAttributes<HTMLNgToastifyContentElement>;
        }
    }
}
